version: '3.7'

services:
  localstack:
    container_name: localstack_hackwire
    image: localstack/localstack:1.1.0
    networks:
      - default
    ports:
      - '4588:4566'
    env_file:
      localstack.env