version: '3.7'
networks:
    fw_backend:
        external: true
services:
  toggle-router:
    container_name: toggle-router
    image: toggle-router
    networks:
      - fw_backend
    ports:
      - '8009:8009'